# ==============================================================================
# docker-compose.yml - TrustShield Enterprise Grade
# Versão: 10.2.0 (Volume Mount Fix)
#
# Otimizações e Melhores Práticas Implementadas:
# - CORREÇÃO: Adicionada a montagem de volumes para os diretórios 'data' e 'outputs'
#   no serviço 'trustshield-api', resolvendo o FileNotFoundError.
# - Uso de extensões YAML (`x-`) para reduzir duplicação (DRY).
# - Healthchecks robustos para garantir a ordem de inicialização correta.
# - Gestão de secrets centralizada para maior segurança.
# ==============================================================================

x-common-settings: &common-settings
  restart: unless-stopped
  networks:
    - trustshield-net

services:
  # --- Banco de Dados para o MLflow ---
  postgres:
    image: postgres:14-alpine
    container_name: trustshield-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_DB=mlflow
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow -d mlflow"]
      interval: 5s
      timeout: 5s
      retries: 10
    <<: *common-settings

  # --- Armazenamento de Artefatos (S3-compatível) ---
  minio:
    image: minio/minio:latest
    container_name: trustshield-minio
    ports:
      - "9000:9000" # Endpoint da API S3
      - "9001:9001" # Console Web
    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/minio_root_user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_root_password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 2s
      retries: 10
    secrets:
      - minio_root_user
      - minio_root_password
    <<: *common-settings

  # --- Serviço de Criação do Bucket do MLflow ---
  # Contêiner efêmero que garante que o bucket 'mlflow' exista no MinIO.
  create-buckets:
    image: minio/mc:latest
    container_name: trustshield-bucket-creator
    depends_on:
      minio:
        condition: service_healthy
    secrets:
      - minio_root_user
      - minio_root_password
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 $$(cat /run/secrets/minio_root_user) $$(cat /run/secrets/minio_root_password);
      mc ls myminio/mlflow || mc mb myminio/mlflow;
      echo 'Bucket mlflow pronto.';
      exit 0;
      "
    networks:
      - trustshield-net

  # --- Servidor de Tracking do MLflow ---
  mlflow:
    build:
      context: .
      dockerfile: mlflow.Dockerfile
    container_name: trustshield-mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID_FILE=/run/secrets/minio_root_user
      - AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/minio_root_password
    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri postgresql://mlflow:postgres@postgres:5432/mlflow
        --default-artifact-root s3://mlflow/
    depends_on:
      postgres:
        condition: service_healthy
      create-buckets:
        condition: service_completed_successfully
    secrets:
      - minio_root_user
      - minio_root_password
    <<: *common-settings

  # --- Serviço Principal: Treinador e API ---
  trustshield-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: trustshield-api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - WAIT_HOSTS=postgres:5432,minio:9000,mlflow:5000
      - WAIT_TIMEOUT=120
      # ---> ADICIONE ESTAS 2 LINHAS PARA O BOTO3 ENCONTRAR OS SEGREDOS <---
      - AWS_ACCESS_KEY_ID_FILE=/run/secrets/minio_root_user
      - AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/minio_root_password
    volumes:
      - ../data:/home/trustshield/data
      - ../outputs:/home/trustshield/outputs
    entrypoint: [ "/home/trustshield/docker/entrypoint.sh" ]
    depends_on:
      mlflow:
        condition: service_started
    # ---> ADICIONE ESTA SEÇÃO DE SECRETS ABAIXO <---
    secrets:
      - minio_root_user
      - minio_root_password
    <<: *common-settings

# --- Rede Compartilhada ---
networks:
  trustshield-net:
    driver: bridge
    name: trustshield-network

# --- Volumes Persistentes ---
volumes:
  postgres_data:
    name: trustshield-postgres-data
  minio_data:
    name: trustshield-minio-data

# --- Gestão de Secrets ---
# Mapeia os ficheiros de segredos locais para serem usados pelos contêineres.
secrets:
  minio_root_user:
    file: ../secrets/minio_root_user.txt
  minio_root_password:
    file: ../secrets/minio_root_password.txt